version: '3.8'

services:
  mongo_club:
    image: mongo:latest
    container_name: mongo_club
    restart: always
    ports:
      - "28017:27017"
    volumes:
      - mongo_club_data:/data/db
    networks:
      - resApp

  api_club:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_club
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo_club
    command: node app.js
    networks:
      - resApp

  client_club:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_club
    restart: always
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - api_club
    volumes:
      - client_club_data:/usr/share/nginx/html  
    networks:
      - resApp

volumes:
  mongo_club_data: {}
  client_club_data:

networks:
  resApp:
    driver: bridge