version: '3.8'

services:
  # Node.js application service
  API:
    image: ./API/Dockerfile
    working_dir: /app
    volumes:
      - API:/app
    depends_on:
      - DB
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=Deployment
  
  Client:
      build: ./Client/DockerfileProd  
      ports:
        - "80:80"  
      volumes:
        - client:/usr/share/nginx/html  
      depends_on: 
        - API
  
  
  DB:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

  DB-monitor:
    image: mongo-express:latest
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: DB://admin:admin@mongodb:27017/
    depends_on:
      - DB

  volumes:
    db_data:
    client:
